[build]
# The index HTML file to drive the bundling process.
target = "static/index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
# For local development keep it as "/"
# GitHub Actions workflow will override this with the correct path during deployment
public_url = "/"

[watch]
# Paths to watch for changes to trigger rebuilds.
watch = ["src/", "static/"]

[serve]
# The addresses to serve on.
addresses = ["127.0.0.1"]
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true

# Add CSS configuration to disable integrity hashes
[css]
integrity = false